### PR TITLE
Updated to lastest ingite version and added ingite wrapper for compatibility

### PR DESCRIPTION
**Pull request by lxgr-linux**
This updates the go, ignite and dependencies

### CODE REVIEW

**Comment by patrickwieth** [comment]
Is this tested with a real blockchain data dump?

**Comment by lxgr-linux** [comment]
No it's not and i isn't even ready yet. I will also incorporate #101 here.

**Comment by lxgr-linux** [comment]
It is now advised to use `./ignite` instead of `ignite` they both take the same arguments.
There was also a `--path <path>` flag added to reference to an ignite version at a different location.

**Comment by lxgr-linux** [comment]
Tested with chain dump

**Pull request merged**
